### ISSUE TITLE
Escaped newlines in attribute values

### ISSUE THREAD

**Issue by benw** [ogham/Rust-BBEdit#3]
If the value of an attribute is a string containing an escaped newline, it is misinterpreted as a premature end of the string. Then the closing double quote is misinterpreted as the start of a new string, and all following code is highlighted as the content of the string.

e.g. from rust /src/libcore/iter.rs:

```
#[rustc_on_unimplemented="a collection of type `{Self}` cannot be \
                          built from an iterator over elements of type `{A}`"]
pub trait FromIterator<A>: Sized {
```

**Comment by ogham** [comment]
OK, so attributes can contain newlines. That's news to me!

**Comment by ogham** [comment]
`git pull` and try again?

**Comment by benw** [comment]
Fixed - Thanks!
